# Generated by Django 4.1.1 on 2022-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=255, null=True)),
                ('profit_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.CharField(blank=True, max_length=255, null=True)),
                ('event_price', models.CharField(blank=True, max_length=255, null=True)),
                ('eveent_sale', models.CharField(blank=True, max_length=255, null=True)),
                ('event_buy', models.CharField(blank=True, max_length=255, null=True)),
                ('ex_profit_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('main_category', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('abc', models.CharField(blank=True, max_length=255, null=True)),
                ('situation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_change', models.CharField(blank=True, max_length=255, null=True)),
                ('last_pur_date', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sale_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
